#!/usr/bin/env python3
"""
Rule-based bill/amendment status classifier.

Congress.gov does not expose a clean, standardized "status" field on the
sponsored-legislation endpoint -- only free-text `latestAction.text`
(the single most recent recorded legislative action). That text follows
fairly formulaic patterns generated by the same congressional
record-keeping process, so -- like GovTrack.us does over the same
underlying data -- it can be classified into a standardized status
taxonomy via pattern matching. This is a text-classification pass only:
no new API calls, applied entirely to already-downloaded data.

Because `latestAction` is the SINGLE most recent action (not a full
history), the classification reflects the most recent known state of the
bill/amendment, not necessarily every stage it passed through.

Input:  sponsored_legislation_full_deduped.csv
Output: sponsored_legislation_full_status.csv  (adds a BillStatus column)
        status_classification_report.txt        (coverage stats)
"""

import csv
import re
from collections import Counter

IN_FILE = "sponsored_legislation_full_deduped.csv"
OUT_FILE = "sponsored_legislation_full_status.csv"
REPORT_FILE = "status_classification_report.txt"

# ---------------------------------------------------------------------
# BILL / RESOLUTION rules, in priority order (first match wins).
# Patterns derived from empirical frequency analysis of latest_action_text
# across all 150,712 Bill/Resolution rows in this dataset.
# ---------------------------------------------------------------------
BILL_RULES = [
    ("Became Law", re.compile(
        r"became (public|private) law|public law no|private law|^public law \d", re.I)),
    # Veto override attempt: check success vs failure of the override itself
    ("Became Law (Veto Overridden)", re.compile(
        r"\boverrid.*\b(agreed to|passed|sustained)\b(?!.{0,40}\bfailed\b)", re.I)),
    ("Vetoed (Veto Not Overridden)", re.compile(
        r"overrid.*\b(failed|rejected|not sustained)\b|"
        r"failed of passage.{0,60}over veto|"
        r"failed.{0,40}\bveto\b", re.I)),
    ("Vetoed by President", re.compile(r"\bvetoed\b|\bpocket vetoed\b", re.I)),
    ("Passed House", re.compile(
        r"^measure passed house\.?$|^passed house\b|"
        r"in the house.{0,60}(read the third time,? and passed|"
        r"considered.{0,10}read the third time.{0,10}passed)", re.I)),
    ("Passed Senate", re.compile(
        r"^measure passed senate\.?$|^passed senate\b|"
        r"in the senate.{0,60}(read the third time,? and passed|"
        r"considered.{0,10}read the third time.{0,10}passed)", re.I)),
    # "Disagreed to in Senate" contains "agreed to in Senate": check it first
    ("Failed/Rejected", re.compile(r"\bdisagreed to\b", re.I)),
    ("Agreed To (Resolution)", re.compile(
        r"(?<!dis)agreed to in (house|senate)|"
        r"^submitted in the senate, considered, and agreed to", re.I)),
    ("Failed/Rejected", re.compile(
        r"failed of passage|failed by (recorded|yea-nay|voice) vote|"
        r"failed by the yeas and nays|"
        r"rejected|not agreed to|defeated|indefinitely postponed|"
        r"cloture.{0,60}not invoked|failed to approve|failed to report favorably|"
        r"motion to (table|proceed).{0,40}(agreed to|rejected|tabled)|"
        r"(?<!reconsider ).{0,10}motion to table\b(?!.{0,30}reconsider)",
        re.I)),
    ("Reported by Committee / On Calendar", re.compile(
        r"ordered.{0,20}reported|reported \(amended\)|reported with amendment|"
        r"placed on .*calendar|reported to (house|senate)|hearings? held|"
        r"hearings? concluded|mark[ -]?up session|approved for full committee|"
        r"filed (a )?(written )?report|returned to the calendar|"
        r"requested executive comment|received executive comment|"
        r"executive comment (requested|received)|"
        r"forwarded (by|to) (sub)?committee|forwarded.{0,20}full committee|"
        r"granted an extension",
        re.I)),
    ("Referred to Committee", re.compile(
        r"referred (jointly )?to (the )?(select |joint |house |senate )?(sub)?committees?|"
        r"^referred to (house|senate) [a-z]", re.I)),
    ("Held at the Desk", re.compile(r"held at (the )?desk", re.I)),
    ("Agreed To (Resolution)", re.compile(
        r"amended\.? agreed to|preamble agreed to|title of the measure was amended", re.I)),
    ("Other Procedural Action", re.compile(
        r"motion to reconsider|laid on the table|sponsor introductory remarks|"
        r"^see also\b|^star print\b|^message on (house|senate) action\b|"
        r"^see [hs]\.?\s?j?\.?\s?r|^for further action|motion to proceed|"
        r"ordered.{0,20}printed as passed|in lieu of this measure|passed .{0,15}in lieu|"
        r"incorporated (this|into|in) (measure|h\.?r)|"
        r"motion to discharge committee|^received in the (house|senate)|"
        r"^conference held|unanimous consent request|errata sheet|"
        r"passed over the measure",
        re.I)),
]

# ---------------------------------------------------------------------
# AMENDMENT rules -- different vocabulary/semantics than bills.
# ---------------------------------------------------------------------
AMDT_RULES = [
    ("Amendment Withdrawn", re.compile(r"withdrawn", re.I)),
    ("Amendment Ruled Out of Order/Non-Germane", re.compile(
        r"ruled (out of order|non-germane)|point of order.{0,80}\bsustained\b|"
        r"ruling of the chair|determined non-germane|determined out of order", re.I)),
    ("Amendment Not Agreed To / Failed", re.compile(
        r"not agreed to|failed of passage|failed by (recorded|yea-nay|voice) vote|"
        r"\bfailed\b|not invoked|rendered moot|fell\s?when|\bvitiated\b|"
        r"\btabled\b|\bell when\b.{0,20}tabled", re.I)),
    ("Amendment Agreed To", re.compile(
        r"agreed to|amendment passed|motion to table agreed to|previously adopted|"
        r"\bconcurred\b|determined germane|debated and passed", re.I)),
    ("Reported by Committee / On Calendar", re.compile(
        r"hearings held|filed (a )?(written )?report", re.I)),
    ("Referred to Committee", re.compile(
        r"referred (jointly )?to (the )?(select |joint |house |senate )?(sub)?committees?", re.I)),
    ("Other Procedural Action", re.compile(
        r"motion to table.{0,60}rejected|motion.{0,20}reconsider.{0,60}rejected|"
        r"reconsider.{0,20}entered in senate|cloture motion presented", re.I)),
    ("Considered / Proposed, No Recorded Disposition", re.compile(
        r"considered by (house|senate)|proposed by (senator|representative)|"
        r"\boffered by (mr|mrs|ms|representative|senator)\b|"
        r"^amendment offered by\b|ordered to be printed|"
        r"modified by unanimous consent", re.I)),
    ("Point of Order Raised (Outcome Not in Text)", re.compile(
        r"point of order", re.I)),
]


def classify_bill(text):
    for label, rx in BILL_RULES:
        if rx.search(text):
            return label
    if not text.strip():
        return "No Recorded Action"
    return "Unclassified"


def classify_amendment(text):
    for label, rx in AMDT_RULES:
        if rx.search(text):
            return label
    if not text.strip():
        return "No Recorded Action"
    return "Unclassified"


def main():
    with open(IN_FILE, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames + ["BillStatus"]
        rows = list(reader)

    bill_counter = Counter()
    amdt_counter = Counter()
    unclassified_bill_samples = []
    unclassified_amdt_samples = []

    for r in rows:
        text = r.get("LatestActionText", "") or ""
        if r["ItemCategory"] == "Bill/Resolution":
            status = classify_bill(text)
            bill_counter[status] += 1
            if status == "Unclassified" and len(unclassified_bill_samples) < 40:
                unclassified_bill_samples.append(text)
        elif r["ItemCategory"] == "Amendment":
            status = classify_amendment(text)
            amdt_counter[status] += 1
            if status == "Unclassified" and len(unclassified_amdt_samples) < 40:
                unclassified_amdt_samples.append(text)
        else:
            status = "Unclassified"
        r["BillStatus"] = status

    with open(OUT_FILE, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(rows)

    total_bills = sum(bill_counter.values())
    total_amdts = sum(amdt_counter.values())

    lines = []
    lines.append("=== BILL/RESOLUTION STATUS CLASSIFICATION (%d rows) ===" % total_bills)
    for label, cnt in bill_counter.most_common():
        lines.append(f"{cnt:8d}  ({cnt/total_bills*100:5.2f}%)  {label}")
    lines.append("")
    lines.append("=== AMENDMENT STATUS CLASSIFICATION (%d rows) ===" % total_amdts)
    for label, cnt in amdt_counter.most_common():
        lines.append(f"{cnt:8d}  ({cnt/total_amdts*100:5.2f}%)  {label}")
    lines.append("")
    lines.append("=== SAMPLE UNCLASSIFIED BILL TEXTS (up to 40) ===")
    for t in unclassified_bill_samples:
        lines.append("  " + t[:160])
    lines.append("")
    lines.append("=== SAMPLE UNCLASSIFIED AMENDMENT TEXTS (up to 40) ===")
    for t in unclassified_amdt_samples:
        lines.append("  " + t[:160])

    report = "\n".join(lines)
    with open(REPORT_FILE, "w", encoding="utf-8") as f:
        f.write(report)
    print(report)


if __name__ == "__main__":
    main()
